// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjymbgosvpgfrtkqdxya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqeW1iZ29zdnBnZnJ0a3FkeHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MjE5NTQsImV4cCI6MjA3NTM5Nzk1NH0.dUl7rQ6rJn-VY2FJNDDTDJsMgdBvc6j1dGzNzEUxWys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});